import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/navbar";
import { bellefair, barlow, barlow_condensed } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Space app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bellefair.variable} ${barlow.variable} ${barlow_condensed.variable}`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
